### ISSUE TITLE
Add administrative files

### ISSUE THREAD

**Issue by cvvergara** [iboates/osm2pgrouting4qgis#12]
@iboates 
We are making all the repos to have the following files:
https://github.com/pgRouting/pgrouting/blob/master/LICENSE
https://github.com/pgRouting/pgrouting/blob/master/CONTRIBUTING.md
https://github.com/pgRouting/pgrouting/blob/master/CODE_OF_CONDUCT.md

This one can be different. Because we haven't set up a coding convention well its up to you now
Later we can decide.
https://github.com/pgRouting/pgRoutingLayer/blob/master/CONTRIBUTING.md

BTW do you know how to add a license in a python file?
I tried something like this:
https://github.com/pgRouting/pgrouting/blob/master/src/dijkstra/dijkstra.c
But it gets as part of the description when I use help(module)

**Comment by iboates** [comment]
Just acknowledging that I have seen this. I recently arrived back home from holiday.

**Comment by iboates** [comment]
https://github.com/pgRouting/osm2pgrouting4qgis/commit/79ce34b0749a7564b4598a2079f86aee6d65d444
